USE MASTER
ALTER DATABASE Dem04DB SET SINGLE_USER WITH ROLLBACK IMMEDIATE
DROP DATABASE IF EXISTS Dem04DB
CREATE DATABASE Dem04DB

USE Dem04DB

CREATE TABLE Clients(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	_Name NVARCHAR(50) NOT NULL,
	_Surname NVARCHAR(50) NOT NULL,
	Number NVARCHAR(10) NOT NULL
)
CREATE TABLE RequestStates(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	RequestState NVARCHAR(15) NOT NULL
)

CREATE TABLE Roles(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	ROLENAME NVARCHAR(50) NOT NULL,
	_IsAdmin BIT NOT NULL
)

CREATE TABLE LOGINS(
	_Login NVARCHAR(50) NOT NULL PRIMARY KEY,
	_Password NVARCHAR(50) NOT NULL,
	_Role INT REFERENCES Roles(ID) NOT NULL,
)

CREATE TABLE Workers(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	_Name NVARCHAR(50) NOT NULL,
	_Surname NVARCHAR(50) NOT NULL,
	Number NVARCHAR(10) NOT NULL,
	_Login NVARCHAR(50) REFERENCES LOGINS(_Login) NOT NULL
)
CREATE TABLE Requests(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	DateOfAccept DATETIME NOT NULL,
	DateOfWorkStart DATETIME,
	DateOfWorkEnd DATETIME,
	RequestDescription NVARCHAR(400),
	RequestState INT REFERENCES RequestStates(ID) NOT NULL,
	Client INT REFERENCES Clients(ID) NOT NULL,
	Worker INT REFERENCES Workers(ID) NOT NULL,
	RequestPriority INT NOT NULL,
)
CREATE TABLE Equipment(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	_Type NVARCHAR(50) NOT NULL,
	SerialNumber NVARCHAR(100) NOT NULL
)
CREATE TABLE EquipmentForRequest(
	RequestID INT REFERENCES Requests(ID) NOT NULL,
	EquipmentID INT REFERENCES Equipment(ID) NOT NULL,
	PRIMARY KEY(RequestID,EquipmentID)
)